name: bumping-versions-pipeline
on:
  push:
    branches:
      - "main"
jobs:
  release:
    name: bumping-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install semantic-release @semantic-release/changelog @semantic-release/git

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_RELEASE }}
        run: npx semantic-release
