name: Tagging

on:
  push:
    branches: ['8.0']
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create an incremental tag
        uses: aurestic/incremental-tag@1.0.8
        with:
          flag_branch: true
          prev_tag: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
